### PR TITLE
Added type stubs

### LINKED ISSUE #31: PEP561 type stubs for mypy
I've written the needed pyi files to type the library. It looks like it would take some pretty big changes to the package structure to make it work with side by side stubs. Would you prefer I keep trying to get it to work side by side? I can also make a stub-only package and give it to you to upload separately? Or would you prefer something else?

### PR DESCRIPTION
**Pull request by xzy3**
Added a stubs project for python types as laid out in PEP561. resolves #31

### CODE REVIEW

**Comment by gfairchild** [comment]
@xzy3, I apologize for how long it's taken for me to review this relatively simple PR. Life has been pretty crazy for a while now.

One concern I have with this is that many things are duplicated (README, most of the `setup.cfg`, LICENSE, etc.). If I want to make a change to any of these, I now need to make that change in 2 places. This doesn't seem right. What are your thoughts?

**Comment by xzy3** [comment]
Technically this is co-hosting two projects with different names in the same repo. The files you've pointed out could be included using a `file:` attribute in the second setup.cfg. The two projects would need to be uploaded separately.

**Comment by gfairchild** [comment]
Hm, I think that might be better. I really don't want to worry about maintaining two separate copies of the same code.

Does this also mean that because it's two projects with different names that I'd have to push two different packaged versions to PyPI? I'm still trying to wrap my head around how this is used in practice.

**Comment by xzy3** [comment]
yes. You would push each package separately. Though I think the -stubs probably aren't going to change much. I don't think the use case of adding types to extension packages has really been fleshed out. At least no one has written about it that I can find.

**Comment by gfairchild** [comment]
Makes sense. I think I'm going to hold off on merging this for now. While the `__init__.pyi` won't be changing unless I modify the root library somehow, `setup.cfg` will change with every iteration (since it contains the version number and other useful PyPI metadata). I really appreciate you putting this together!

**Comment by xzy3** [comment]
I made the updates to setup.cfg

**Comment by gfairchild** [comment]
> I made the updates to setup.cfg

Thanks for these changes! I'm still curious of there's a way to consolidate `setup.cfg` and the root [`setup.py`](setup.py) to eliminate redundancy altogether.

**Comment by xzy3** [comment]
Not that I particularly found. That's what about 90% of this thread has been about. I might have missed something though.

**Comment by gfairchild** [comment]
> Not that I particularly found. That's what about 90% of this thread has been about. I might have missed something though.

Yeah, and I may just being too picky here. My complaint really isn't all that serious. Just kind of annoying to me that there's not a more efficient way of designing this (that we can tell). I may just merge and call it good enough (don't let the good be the enemy of the perfect).

**Comment by maxbachmann** [comment]
I do not understand why you even want to ship the type stubs as a separate project. Why not just include them in the normal installation?

**Comment by gfairchild** [comment]
> I do not understand why you even want to ship the type stubs as a separate project. Why not just include them in the normal installation?

My main hesitation with this is that it's duplicating several files, and if an update were made to one of them in the future, I'd need to remember to update the duplicate as well.

**Comment by gfairchild** [comment]
Closing this because it was implemented in #37. Thank you, @xzy3!

**Pull request closed without merging**
