### PR TITLE
add type stubs

### PR DESCRIPTION
**Pull request by maxbachmann**
@gfairchild this is how I implement installation + type stubs in my projects. This avoids the duplication from https://github.com/lanl/pyxDamerauLevenshtein/pull/34.

The only duplicated file is the actual type hint, which can't be avoided when working with c extensions.

### CODE REVIEW

**Comment by gfairchild** [comment]
Nice! At first glance, this is pretty much what I was hoping for with no duplication.

**Comment by gfairchild** [comment]
Do you know how we can test this? It'd be great to incorporate something into the current unit-testing framework.

**Comment by maxbachmann** [comment]
I have the following test in my projects:
https://github.com/maxbachmann/RapidFuzz/blob/f69be93ca84e28354d16c874cb0b2d6407f238cd/.github/workflows/branchbuild.yml#L117-L120

**Comment by gfairchild** [comment]
> I have the following test in my projects: https://github.com/maxbachmann/RapidFuzz/blob/f69be93ca84e28354d16c874cb0b2d6407f238cd/.github/workflows/branchbuild.yml#L117-L120

That's great. Thanks!

**Comment by maxbachmann** [comment]
@gfairchild are there any plans to geht this merged? Otherwise I will close the PR.

**Comment by gfairchild** [comment]
I apologize. I'd love to spend more time reviewing this, but I just haven't had time. I don't really use this code base much anymore.

I'd prefer to leave the PR open instead of close.

**Comment by maxbachmann** [comment]
Unless I have a special interest in a PR, I close them at some point around the 1 year mark. However feel free to merge this into a branch and create your own PR you can look into if you ever find the time.

**Comment by gfairchild** [comment]
I'm going to go ahead and merge. Thank you, @maxbachmann, for your contribution, and I apologize for how long it took me to act on this.

**Pull request merged**
